modified2

diff --git a/02-functions b/02-functions
--- a/02-functions
+++ b/02-functions
@@ -1,16 +1,18 @@
 #!/bin/bash
 USERID=$(id -u)
-if[ USERID -ne 0 ]
+if [USERID -ne 0]
+then
  echo "please run the script with root user"
  exit 1
 fi
 yum list installed git
-if[$? -ne 0]
+if [$? -ne 0]
+then
   echo "git is already installed"
  else
  yum install git -y
-  if[$? -ne 0] 
-    echo "git is filed to install"
+  if [$? -ne 0] 
+    echo "git is failed to install"
    else
    echo "git is successfully installed"
   fi
